services:
  vllm:
    image: vllm/vllm-openai:cu130-nightly
    container_name: ${CONTAINER_NAME:-vllm}
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    #entrypoint: ["vllm", "serve"]
    environment:
      - VLLM_NVFP4_GEMM_BACKEND=marlin
      - VLLM_ALLOW_LONG_MAX_MODEL_LEN=${VLLM_ALLOW_LONG_MAX_MODEL_LEN:-0}
      - VLLM_FLASHINFER_ALLREDUCE_BACKEND=trtllm
      - VLLM_USE_FLASHINFER_MOE_FP4=0
    volumes:
      - ${HF_CACHE_DIR:-~/.cache/huggingface}:/root/.cache/huggingface
      - ./reasoning_parsers:/app/reasoning_parsers
    ports:
      - "${VLLM_PORT:-8000}:${VLLM_PORT:-8000}"
    command: >
      --model ${VLLM_MODEL:-nvidia/NVIDIA-Nemotron-3-Super-120B-A12B-NVFP4}
      --served-model-name ${VLLM_SERVED_MODEL_NAME:-nemotron-3-super}
      --host 0.0.0.0
      --port ${VLLM_PORT:-8000}
      --dtype auto
      --kv-cache-dtype ${VLLM_KV_CACHE_DTYPE:-fp8}
      --tensor-parallel-size 1
      --pipeline-parallel-size 1
      --data-parallel-size 1
      --trust-remote-code
      --gpu-memory-utilization ${VLLM_GPU_MEMORY_UTILIZATION:-0.80}
      --enable-chunked-prefill
      --max-num-seqs ${VLLM_MAX_NUM_SEQS:-4}
      --max-model-len ${VLLM_MAX_MODEL_LEN:-262144}
      --moe-backend marlin
      --mamba_ssm_cache_dtype ${MAMBA_SSM_CACHE_DTYPE:-float32}
      --quantization fp4
      --speculative_config ${SPECULATIVE_CONFIG:-{"method":"mtp","num_speculative_tokens":3,"moe_backend":"triton"}}
      --reasoning-parser-plugin ${VLLM_REASONING_PARSER_PLUGIN:-/app/reasoning_parsers/super_v3_reasoning_parser.py}
      --reasoning-parser ${VLLM_REASONING_PARSER:-super_v3}
      --enable-auto-tool-choice
      --tool-call-parser ${VLLM_TOOL_CALL_PARSER:-qwen3_coder}
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
