services:
  github-runner:
    image: ghcr.io/actions/actions-runner:latest
    container_name: ${CONTAINER_NAME}
    entrypoint: ["/bin/bash", "-c", "./config.sh --unattended --url ${REPO_URL} --token ${RUNNER_TOKEN} ${RUNNER_NAME:+--name ${RUNNER_NAME}} ${RUNNER_LABELS:+--labels ${RUNNER_LABELS}} && ./run.sh"]
    environment:
      - REPO_URL=${REPO_URL}
      - RUNNER_TOKEN=${RUNNER_TOKEN}
      - RUNNER_NAME=${RUNNER_NAME}
      - RUNNER_LABELS=${RUNNER_LABELS}
    restart: unless-stopped
    # in case you need to reach the docker host at "host.docker.internal" inside the runner
    #extra_hosts:
    #  - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          cpus: '${CPUS}'
          memory: ${MEMORY}
