services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:cuda
    container_name: open-webui
    ports:
      - "${OPENWEBUI_PORT}:8080"
    environment:
      - ENABLE_SIGNUP=true
      - CORS_ALLOW_ORIGIN=${CORS_ALLOW_ORIGIN}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - RAG_OLLAMA_BASE_URL=${RAG_OLLAMA_BASE_URL}
      - RAG_EMBEDDING_ENGINE=${RAG_EMBEDDING_ENGINE}
      - RAG_EMBEDDING_MODEL=${RAG_EMBEDDING_MODEL}
      - ENABLE_RAG_WEB_SEARCH=${ENABLE_RAG_WEB_SEARCH}
      - RAG_WEB_SEARCH_ENGINE=${RAG_WEB_SEARCH_ENGINE}
      - RAG_WEB_SEARCH_RESULT_COUNT=${RAG_WEB_SEARCH_RESULT_COUNT}
    restart: unless-stopped
    volumes:
      - open-webui:/app/backend/data
    extra_hosts:
      - "host.docker.internal:host-gateway" # Add host.docker.internal for accessing the host machine
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]


volumes:
  open-webui:
