print_iter_log: false

#max_num_tokens: 262144
kv_cache_config:
  dtype: "fp8"
  free_gpu_memory_fraction: 0.80
#  enable_block_reuse: true

enable_chunked_prefill: true

cuda_graph_config:
  enable_padding: true
#  max_batch_size: 256

disable_overlap_scheduler: false
#num_postprocess_workers: 4
#enable_iter_perf_stats: true
