services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8053:80/tcp"
    environment:
      TZ: '${TIMEZONE}'
      WEBPASSWORD: ${WEB_PASSWORD}
    volumes:
      - '${ETC_PIHOLE}:/etc/pihole'
      - '${ETC_DNSMASQ}:/etc/dnsmasq.d'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '256M'
