services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "${PIHOLE_PORT}:8053/tcp"
    environment:
      TZ: ${TIMEZONE}
      FTLCONF_webserver_api_password: '${WEB_PASSWORD}'
      FTLCONF_dns_upstreams: '${PIHOLE_DNS_UPSTREAMS}'
      FTLCONF_webserver_port: '8053,443s'
    volumes:
      - pihole:/etc/pihole
      - dnsmasq:/etc/dnsmasq.d
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '512M'

volumes:
  pihole:
  dnsmasq:
