[global]
check_update=false

[cpu]
enable=true

[mem]
enable=true

[gpu]
enable=true

[diskio]
enable=true

[fs]
enable=true

[network]
enable=true

[sensors]
enable=true
# Uncomment and adjust if you want to filter specific sensors:
# hide=Virtual_0,acpitz

[hddtemp]
enable=false