services:
  ddclient:
    image: lscr.io/linuxserver/ddclient:latest
    container_name: ddclient
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${DDCLIENT_CONFIG}:/config
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '128M'
