services:
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '8080:80'
      - '8443:443'
      - '8081:81'
    volumes:
      - ${NGINX_PROXY_MANAGER_DATA}:/data
      - ${LETSENCRYPT}:/etc/letsencrypt
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '512M'
