services:
  crowdsec:
    image: crowdsecurity/crowdsec:v1.7.6
    container_name: crowdsec
    restart: unless-stopped
    networks:
      - public
    environment:
      COLLECTIONS: "crowdsecurity/traefik"
      CUSTOM_HOSTNAME: crowdsec
      # Must match the key in traefik/configurations/dynamic.yml crowdsec-bouncer middleware
      BOUNCER_KEY_TRAEFIK: ${CROWDSEC_BOUNCER_KEY}
    volumes:
      - ./acquis.yaml:/etc/crowdsec/acquis.yaml:ro
      - ${TRAEFIK_LOG_PATH}:/var/log/traefik:ro
      - ${CROWDSEC_DB_PATH}:/var/lib/crowdsec/data/
      - ${CROWDSEC_CONFIG_PATH}:/etc/crowdsec/
    labels:
      - "traefik.enable=false"

networks:
  public:
    external: true
